workflows:
  build:
    name: Build Android
    environment:
      node: latest
      flutter: stable
      # Spécifiez votre version de Java si nécessaire
      java: openjdk11
      # Vous pouvez ajouter d'autres dépendances ici si besoin
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build APK
        script: |
          npx expo prebuild
          npx expo build:android
    artifacts:
      - build/**/app-release.apk  # Chemin vers votre APK final

